### ISSUE TITLE
Add metalinter support

### ISSUE THREAD

**Issue by sridharv** [surullabs/lint#2]
Add it initially with all linters disabled and have users pick the ones they want manually.

**Comment by fortytw2** [comment]
It could be really nifty to do this, then vendor `gometalinter` into a `internal/` folder, so that anyone importing / vendoring this repo wouldn't have any dependency on external versions / internet access

**Comment by sridharv** [comment]
That's a good idea. We'd have to do it so that anyone using it is also able to override the vendored binaries. I'll have to play around with how the vendor directory interacts with binaries. However, we should be able to bypass the Go vendoring system entirely and just install binaries with different names. I'll open a separate issue to track that since a sensible solution for vendoring linters will carry over to this as well.

**Comment by fortytw2** [comment]
Well, not vendor the binaries, but the code from the linters themselves :)

**Comment by sridharv** [comment]
Well yes :) Even that needs to be overridable.

**Comment by sridharv** [comment]
I've started prototyping this in the metalinter branch.

**Comment by sridharv** [comment]
@fortytw2 Thanks for the suggestion to vendor gometalinter. It proved very helpful.

**Comment by fortytw2** [comment]
@sridharv anytime :) will finally have a change to give this package a try today :dancer:
