### ISSUE TITLE
Support vendoring linters

### ISSUE THREAD

**Issue by sridharv** [surullabs/lint#3]
As suggested by @fortytw2 in #2, vendoring linters (especially gometalinter) will make it much easier to run this as part of a test suite since no internet access is needed.

## Requirements

 - Vendoring will need to be done so that it can be easily overridden if necessary.
 - It should work independently of any package managers.
 - There is no requirement that it use the Go vendoring system

**Comment by matrixik** [comment]
Looks like gometalinter is already doing at last part of that:
https://github.com/alecthomas/gometalinter/tree/master/vendor

**Comment by sridharv** [comment]
Yup. We can use that for gometalinter, but I'd like to also have a plan in place for vendoring linters that aren't a part of gometalinter.

**Comment by sridharv** [comment]
@matrixik Thanks for the pointer to gometalinter's vendoring. I knew it was vendoring the linters, but hadn't taken a deeper look into how. I was able to use the same model to vendor gometalinter itself.

The vendoring mechanism used in the gometalinter package should be sufficient for any future linter vendoring.

**Comment by matrixik** [comment]
Thanks.
